---
title: "R Notebook"
output: html_notebook
---

```{r setup, include = F}
knitr::opts_chunk$set(echo = T)
```

```{r message = F, warning = F, results = "hide"}
library(targets)
library(tidyverse)
library(torch)
library(luz)
library(tidymodels)
```

```{r}
JeuDonnees_train <- tar_read(JeuDonnees_train)
```

```{r}
train_indices <- 1:25000
valid_indices <- 25001:32500
test_indices <- 32501:40000

data_nn <- left_join(JeuDonnees_train$classic_ml_data, JeuDonnees_train$nn_data, by = "vin")

train_df <- data_nn[train_indices, ]
valid_df <- data_nn[valid_indices, ]
test_df <- data_nn[test_indices, ]
```


```{r}
x <- train_df %>% select(expo:years_licensed, distance)

rec <- 
  recipe(~ ., data = x) %>% 
  step_impute_median(commute_distance, years_claim_free) %>% 
  step_other(all_nominal(), threshold = 0.05) %>% 
  step_dummy(all_nominal())

rec %>% prep() %>% bake(new_data = x)

```



```{r}
nn_dataset <- 
  dataset(
    name = "nn_dataset",
    
    initialize = function(df) {
      data <- self$prepare_data(df)
      
      self$tele <- data$x$tele
      self$class <- data$x$class
      self$y <- data$y
    },
    
    .getitem = function(i) {
      list(
        x = list(
          tele = self$tele[i, ], 
          class = self$class[i, ]
        ), 
        y = self$y[i, ]
      )
    },
    
    .length = function() {
      self$y$size()[[1]]
    },
    
    prepare_data = function(df) {
      target_col <- 
        df$claim_ind_cov_1_2_3_4_5_6 %>% 
        as.integer() %>%
        `-`(1) %>%
        as.matrix()
      
      tele_cols <- 
        df %>%
        select(starts_with(c("h_", "p_", "vmo", "vma"))) %>%
        as.matrix()
    
      class_df <- select(df, expo:years_licensed, distance)
      
      rec_class <-
        recipe(~ ., data = class_df) %>%
        step_impute_median(commute_distance, years_claim_free) %>%
        step_other(all_nominal(), threshold = 0.05) %>%
        step_dummy(all_nominal()) %>%
        prep()

      class_cols <- juice(rec_class) %>% as.matrix()
      
      list(
        x = list(
          tele = torch_tensor(tele_cols),
          class = torch_tensor(class_cols)
        ),
        y = torch_tensor(target_col)
      )
    }
)
```

```{r}
train_ds <- nn_dataset(train_df)
valid_ds <- nn_dataset(valid_df)
test_ds <- nn_dataset(test_df)
```

```{r}
train_dl <- train_ds %>% dataloader(batch_size = 128, shuffle = F)
valid_dl <- valid_ds %>% dataloader(batch_size = 128, shuffle = F)
test_dl <- test_ds %>% dataloader(batch_size = 128, shuffle = F)
```

```{r}
classif_mlp <- 
  nn_module(
    "classif_mlp",
    
    initialize = function(input_size_tele, input_size_class, emb_size = 2) {
      self$bn0 = nn_batch_norm1d(input_size_tele)
      self$linear1 = nn_linear(input_size_tele, 32)
      self$bn1 = nn_batch_norm1d(32)
      self$linear2 = nn_linear(32, 8)
      self$bn2 = nn_batch_norm1d(8)
      self$linear3 = nn_linear(8, emb_size)
      self$bn3 = nn_batch_norm1d(emb_size + input_size_class)
      self$linear4 = nn_linear(emb_size + input_size_class, 1)
    },
    
    extract_embedding = function(x) {
      x$tele %>%
        self$bn0() %>% 
        self$linear1() %>%
        nnf_relu() %>%
        self$bn1() %>% 
        self$linear2() %>%
        nnf_relu() %>%
        self$bn2() %>% 
        self$linear3() %>% 
        nnf_sigmoid()
    },

    forward = function(x) {
      x %>% 
        self$extract_embedding() %>% 
        list(., x$class) %>% 
        torch_cat(dim = 2) %>% 
        self$bn3() %>% 
        self$linear4() %>%
        nnf_sigmoid()
    }
)
```

```{r}
net <- classif_mlp$new(input_size_tele = 61, input_size_class = 16)
input <- train_ds$.getitem(1:10)$x
net$forward(input)
```

```{r}
fit <- 
  classif_mlp %>%
  setup(
    loss = nnf_binary_cross_entropy,
    optimizer = optim_adam,
    metrics = list(luz_metric_binary_auroc(thresholds = seq(0, 0.5, by = 0.0005)), luz_metric_mse())
  ) %>%
  set_hparams(input_size_tele = 61, input_size_class = 16) %>% 
  luz::fit(
    train_dl, 
    epochs = 1, 
    valid_data = valid_dl
  )
```




